#!/bin/bash

clear

project_name=$1
project_head_name=$project_name".h"
project_src_name=$project_name".c"
project_test_name="test_"$project_name"_func.c"

root_dir="~/c/"

bin_dir=$root_dir"bin/"
lib_dir=$root_dir"depend/lib/"
include_dir=$root_dir"depend/include/"

mk_context="
#!/bin/bash \n\n
clear \n

rm $bin_dir$project_name.o  \n\n

gcc -I $include_dir -o $bin_dir$project_name.o \ \n
	 $project_test_name $project_src_name		\n\n

chmod a+x $bin_dir$project_name.o \n\n
$bin_dir$project_name.o \n\n


"

cp -r tmp ./$project_name
mv ./$project_name/tmp.h ./$project_name/$project_head_name
mv ./$project_name/tmp.c ./$project_name/$project_src_name
mv ./$project_name/test_tmp_func.c ./$project_name/$project_test_name

echo -e $mk_context > ./$project_name/mk


