#!/bin/bash

clear

src_name=$1
root=~/c/data_struct/

bin=$root\bin/
inc=$root\include/
src=$root\src/
lib=$root\lib/
tes=$root\test/
mk=$root\mk/

tes_src=test_$src_name

test_file=$tes$tes_src.c
src_file=$src$src_name.c
exe_file=$bin$tes_src.o

lib_file=lib$src_name.so

rm $exe_file

#create lib.so
gcc $src_file					\
-g								\
-I $inc							\
-L $lib							\
-Wl,-rpath $lib					\
-fPIC -shared					\
-o $lib$lib_file

#create test.o
gcc $test_file					\
-g								\
-I $inc							\
-L $lib							\
-Wl,-rpath $lib					\
-l $src_name					\
-l final_link					\
-o $exe_file

chmod a+x $exe_file
$exe_file
